module.exports = {
  modules: {
    'genesys-utils': {},
    'genesys-tasks': {},
    'genesys-launder': {},
    'genesys-i18n': {},
    'genesys-db': {},
    'genesys-locks': {},
    'genesys-caches': {},
    'genesys-migrations': {},
    'genesys-express': {},
    'genesys-urls': {},
    'genesys-templates': {},
    'genesys-email': {},
    'genesys-push': {},
    'genesys-permissions': {},
    'genesys-assets': {},
    'genesys-admin-bar': {},
    'genesys-login': {},
    // After login, so it can install the CSRF middleware exported by genesys-express and still have it
    // be able to check req.user first
    'genesys-csrf': {},
    'genesys-notifications': {},
    'genesys-browser-utils': {},
    'genesys-ui': {},
    'genesys-schemas': {},
    'genesys-docs': {},
    'genesys-jobs': {},
    'genesys-versions': {},
    'genesys-tags': {},
    'genesys-modal': {},
    'genesys-attachments': {},
    'genesys-oembed': {},
    'genesys-pager': {},
    // global comes first so it can register a doc type manager and clean things up before
    // pages claims any orphan page types
    'genesys-global': {},
    'genesys-polymorphic-manager': {},
    'genesys-pages': {},
    'genesys-search': {},
    'genesys-any-page-manager': {},
    'genesys-areas': {},
    'genesys-rich-text-widgets': {},
    'genesys-html-widgets': {},
    'genesys-video-fields': {},
    'genesys-video-widgets': {},
    'genesys-groups': {},
    'genesys-users': {},
    'genesys-images': {},
    'genesys-images-widgets': {},
    'genesys-files': {},
    'genesys-files-widgets': {},
    'genesys-soft-redirects': {},
    // ALWAYS LAST FOREVER
    'genesys-service-bridge': {}
  }
};
